CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519115531_InitialCreate') THEN
    CREATE TABLE public."AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519115531_InitialCreate') THEN
    CREATE TABLE public."AspNetUsers" (
        "Id" text NOT NULL,
        "NombreCompleto" text NOT NULL,
        "Rol" text NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519115531_InitialCreate') THEN
    CREATE TABLE public."Bautismos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FechaBautismo" date NOT NULL,
        "NombreBautizado" character varying(100) NOT NULL,
        "ApellidoPaterno" character varying(100) NOT NULL,
        "ApellidoMaterno" character varying(100),
        "FechaNacimiento" date,
        "NombrePadre" character varying(150),
        "NombreMadre" character varying(150),
        "Padrino" character varying(150),
        "Madrina" character varying(150),
        "Ministro" character varying(150),
        "Libro" character varying(50),
        "Folio" character varying(50),
        "Acta" character varying(50),
        "Observaciones" character varying(500),
        "FechaRegistro" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Bautismos" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519115531_InitialCreate') THEN
    CREATE TABLE public."Confirmaciones" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FechaConfirmacion" date NOT NULL,
        "NombreConfirmado" character varying(100) NOT NULL,
        "ApellidoPaterno" character varying(100) NOT NULL,
        "ApellidoMaterno" character varying(100),
        "NombrePadre" character varying(150),
        "NombreMadre" character varying(150),
        "Padrino" character varying(150),
        "Ministro" character varying(150),
        "Obispo" character varying(150),
        "Libro" character varying(50),
        "Folio" character varying(50),
        "Acta" character varying(50),
        "Observaciones" character varying(500),
        "FechaRegistro" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Confirmaciones" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519115531_InitialCreate') THEN
    CREATE TABLE public."Matrimonios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FechaMatrimonio" date NOT NULL,
        "NombreNovio" character varying(150) NOT NULL,
        "NombreNovia" character varying(150) NOT NULL,
        "PadreNovio" character varying(150),
        "MadreNovio" character varying(150),
        "PadreNovia" character varying(150),
        "MadreNovia" character varying(150),
        "Testigo1" character varying(150),
        "Testigo2" character varying(150),
        "Ministro" character varying(150),
        "Libro" character varying(50),
        "Folio" character varying(50),
        "Acta" character varying(50),
        "Observaciones" character varying(500),
        "FechaRegistro" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Matrimonios" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519115531_InitialCreate') THEN
    CREATE TABLE public."Personas" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" character varying(100) NOT NULL,
        "ApellidoPaterno" character varying(100) NOT NULL,
        "ApellidoMaterno" character varying(100),
        "FechaNacimiento" date NOT NULL,
        "LugarNacimiento" character varying(200),
        "Domicilio" character varying(200),
        CONSTRAINT "PK_Personas" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519115531_InitialCreate') THEN
    CREATE TABLE public."AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519115531_InitialCreate') THEN
    CREATE TABLE public."AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519115531_InitialCreate') THEN
    CREATE TABLE public."AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519115531_InitialCreate') THEN
    CREATE TABLE public."AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519115531_InitialCreate') THEN
    CREATE TABLE public."AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519115531_InitialCreate') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519115531_InitialCreate') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519115531_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519115531_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519115531_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519115531_InitialCreate') THEN
    CREATE INDEX "EmailIndex" ON public."AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519115531_InitialCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260519115531_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260519115531_InitialCreate', '8.0.0');
    END IF;
END $EF$;
COMMIT;

